openapi: 3.0.0
info:
  title: Docker Ecr Publish Buildkite Plugin
  x-cortex-tag: docker-ecr-publish-buildkite-plugin
  x-cortex-type: infra
  description: 'A Buildkite plugin to build, tag, and push Docker images to Amazon ECR. Based on seek-oss/docker-ecr-publish-buildkite-plugin which is no longer supported.'
  x-cortex-git:
    github:
      repository: ROKT/docker-ecr-publish-buildkite-plugin
  x-cortex-owners:
  - type: group
    name: rokt-global-infrastructure
    provider: CORTEX
  x-cortex-groups:
    - lang-shell
    - "serviceTier-3"
  x-cortex-oncall:
    opsgenie:
      type: SCHEDULE
      id: Rokt Global Infrastructure Build and Release_schedule
